-- 테이블 스페이스 생성
-- 크기 10 MB , 용량이 꽉찼을때 2MB의 크기로 자동으로 증가 
CREATE TABLESPACE appservice
DATAFILE 'C:\_appserviceproject\tableSpace\appservice.dbf'
SIZE 10M AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;


-- 계정 생성하기 
CREATE USER greenday IDENTIFIED BY greenday
DEFAULT TABLESPACE appservice
TEMPORARY TABLESPACE temp;

-- 유저 권한 부여
GRANT RESOURCE, CONNECT, CREATE VIEW, CREATE SEQUENCE, CREATE TABLE, CREATE PROCEDURE TO greenday;
